import { Category } from "./types";

const catalog: Record<Category, Record<string, string[]>> = {
  "video-game": {
    "switch": [
      "The Legend of Zelda: Tears of the Kingdom",
      "The Legend of Zelda: Breath of the Wild",
      "Mario Kart 8 Deluxe",
      "Animal Crossing: New Horizons",
      "Super Mario Odyssey",
      "Pokémon Scarlet",
      "Pokémon Violet",
      "Pokémon Legends: Arceus",
      "Metroid Dread",
      "Splatoon 3",
      "Kirby and the Forgotten Land",
      "Super Smash Bros. Ultimate",
      "Fire Emblem: Three Houses",
      "Xenoblade Chronicles 3",
      "Bayonetta 3",
      "Pikmin 4",
      "Luigi's Mansion 3",
      "Ring Fit Adventure",
      "Astral Chain",
      "Monster Hunter Rise",
    ],
    "switch-2": [
      "Mario Kart World",
      "Donkey Kong Bananza",
      "The Legend of Zelda: Breath of the Wild (Switch 2 Edition)",
    ],
    "wii-u": [
      "Super Mario 3D World",
      "Mario Kart 8",
      "Super Smash Bros. for Wii U",
      "Donkey Kong Country: Tropical Freeze",
      "Splatoon",
      "The Legend of Zelda: Wind Waker HD",
      "The Legend of Zelda: Twilight Princess HD",
      "Pikmin 3",
      "Xenoblade Chronicles X",
      "Bayonetta 2",
    ],
    "wii": [
      "Super Mario Galaxy",
      "Super Mario Galaxy 2",
      "The Legend of Zelda: Skyward Sword",
      "The Legend of Zelda: Twilight Princess",
      "Mario Kart Wii",
      "Super Smash Bros. Brawl",
      "Wii Sports",
      "Wii Sports Resort",
      "Metroid Prime 3: Corruption",
      "Xenoblade Chronicles",
      "Donkey Kong Country Returns",
      "New Super Mario Bros. Wii",
      "Kirby's Epic Yarn",
      "Punch-Out!!",
      "Resident Evil 4 (Wii Edition)",
    ],
    "gamecube": [
      "The Legend of Zelda: Wind Waker",
      "The Legend of Zelda: Twilight Princess",
      "Metroid Prime",
      "Metroid Prime 2: Echoes",
      "Super Mario Sunshine",
      "Super Smash Bros. Melee",
      "Mario Kart: Double Dash!!",
      "Luigi's Mansion",
      "Pikmin",
      "Pikmin 2",
      "Fire Emblem: Path of Radiance",
      "Paper Mario: The Thousand-Year Door",
      "Animal Crossing",
      "Resident Evil 4",
      "Eternal Darkness: Sanity's Requiem",
      "F-Zero GX",
      "Viewtiful Joe",
      "Skies of Arcadia Legends",
      "Baten Kaitos: Eternal Wings and the Lost Ocean",
    ],
    "n64": [
      "The Legend of Zelda: Ocarina of Time",
      "The Legend of Zelda: Majora's Mask",
      "Super Mario 64",
      "Mario Kart 64",
      "Super Smash Bros.",
      "Donkey Kong 64",
      "Banjo-Kazooie",
      "Banjo-Tooie",
      "GoldenEye 007",
      "Perfect Dark",
      "Star Fox 64",
      "Paper Mario",
      "Mario Party",
      "Mario Party 2",
      "Mario Party 3",
      "Conker's Bad Fur Day",
      "Pokémon Snap",
      "Pokémon Stadium",
      "Kirby 64: The Crystal Shards",
    ],
    "snes": [
      "Super Mario World",
      "Super Mario RPG: Legend of the Seven Stars",
      "The Legend of Zelda: A Link to the Past",
      "Super Metroid",
      "Donkey Kong Country",
      "Donkey Kong Country 2",
      "Donkey Kong Country 3",
      "Final Fantasy VI",
      "Chrono Trigger",
      "EarthBound",
      "F-Zero",
      "Mega Man X",
      "Mega Man X2",
      "Mega Man X3",
      "Star Fox",
      "Kirby Super Star",
      "Kirby's Dream Land 3",
      "Secret of Mana",
      "Lufia II: Rise of the Sinistrals",
    ],
    "nes": [
      "Super Mario Bros.",
      "Super Mario Bros. 2",
      "Super Mario Bros. 3",
      "The Legend of Zelda",
      "Zelda II: The Adventure of Link",
      "Metroid",
      "Mega Man 2",
      "Mega Man 3",
      "Castlevania",
      "Castlevania III: Dracula's Curse",
      "Contra",
      "DuckTales",
      "Kirby's Adventure",
      "Final Fantasy",
      "Tecmo Super Bowl",
      "Battletoads",
      "Little Samson",
      "Ducktales 2",
      "Chip 'n Dale Rescue Rangers",
    ],
    "game-boy": [
      "Pokémon Red",
      "Pokémon Blue",
      "Pokémon Yellow",
      "Pokémon Gold",
      "Pokémon Silver",
      "Pokémon Crystal",
      "The Legend of Zelda: Link's Awakening",
      "Kirby's Dream Land",
      "Kirby's Dream Land 2",
      "Tetris",
      "Super Mario Land",
      "Super Mario Land 2",
      "Donkey Kong",
      "Metroid II: Return of Samus",
    ],
    "gba": [
      "Pokémon FireRed",
      "Pokémon LeafGreen",
      "Pokémon Ruby",
      "Pokémon Sapphire",
      "Pokémon Emerald",
      "The Legend of Zelda: The Minish Cap",
      "Metroid Fusion",
      "Metroid: Zero Mission",
      "Castlevania: Aria of Sorrow",
      "Castlevania: Circle of the Moon",
      "Final Fantasy VI Advance",
      "Golden Sun",
      "Golden Sun: The Lost Age",
      "Mother 3",
      "Fire Emblem",
      "Fire Emblem: The Sacred Stones",
    ],
    "ds": [
      "Pokémon Diamond",
      "Pokémon Pearl",
      "Pokémon Platinum",
      "Pokémon HeartGold",
      "Pokémon SoulSilver",
      "The Legend of Zelda: Phantom Hourglass",
      "The Legend of Zelda: Spirit Tracks",
      "Chrono Trigger",
      "Mario Kart DS",
      "New Super Mario Bros.",
      "Castlevania: Dawn of Sorrow",
      "Castlevania: Portrait of Ruin",
      "Professor Layton and the Curious Village",
      "Radiant Historia",
      "Dragon Quest IX",
    ],
    "3ds": [
      "Pokémon X",
      "Pokémon Y",
      "Pokémon Omega Ruby",
      "Pokémon Alpha Sapphire",
      "Pokémon Sun",
      "Pokémon Moon",
      "The Legend of Zelda: A Link Between Worlds",
      "The Legend of Zelda: Ocarina of Time 3D",
      "Fire Emblem: Awakening",
      "Fire Emblem Fates",
      "Xenoblade Chronicles 3D",
      "Metroid: Samus Returns",
      "Luigi's Mansion: Dark Moon",
      "Kid Icarus: Uprising",
      "Animal Crossing: New Leaf",
    ],
    "ps5": [
      "Marvel's Spider-Man 2",
      "Marvel's Spider-Man: Miles Morales",
      "God of War Ragnarök",
      "Demon's Souls",
      "Returnal",
      "Ratchet & Clank: Rift Apart",
      "Horizon Forbidden West",
      "Gran Turismo 7",
      "Final Fantasy XVI",
      "Final Fantasy VII Rebirth",
      "Stellar Blade",
      "Astro's Playroom",
      "Bloodborne (PS5 Patch)",
      "The Last of Us Part I",
    ],
    "ps4": [
      "God of War",
      "Marvel's Spider-Man",
      "The Last of Us Remastered",
      "The Last of Us Part II",
      "Horizon Zero Dawn",
      "Ghost of Tsushima",
      "Bloodborne",
      "Uncharted 4: A Thief's End",
      "Red Dead Redemption 2",
      "The Witcher 3: Wild Hunt",
      "Dark Souls III",
      "Sekiro: Shadows Die Twice",
      "Persona 5 Royal",
      "Dragon Quest XI",
      "NieR: Automata",
    ],
    "ps3": [
      "The Last of Us",
      "Uncharted 2: Among Thieves",
      "Uncharted 3: Drake's Deception",
      "Metal Gear Solid 4",
      "Demon's Souls",
      "Persona 5",
      "Ni no Kuni: Wrath of the White Witch",
      "Valkyria Chronicles",
      "3D Dot Game Heroes",
      "Folklore",
    ],
    "ps2": [
      "Shadow of the Colossus",
      "Ico",
      "Kingdom Hearts",
      "Kingdom Hearts II",
      "Final Fantasy X",
      "Final Fantasy XII",
      "God of War",
      "God of War II",
      "Devil May Cry 3",
      "Okami",
      "Katamari Damacy",
      "Silent Hill 2",
      "Persona 4",
      "Persona 3 FES",
      "Dragon Quest VIII",
    ],
    "ps1": [
      "Final Fantasy VII",
      "Final Fantasy VIII",
      "Final Fantasy IX",
      "Castlevania: Symphony of the Night",
      "Metal Gear Solid",
      "Crash Bandicoot",
      "Spyro the Dragon",
      "Tekken 3",
      "Resident Evil 2",
      "Resident Evil 3",
      "Silent Hill",
      "Xenogears",
      "Vagrant Story",
      "Suikoden II",
    ],
    "psp": [
      "God of War: Chains of Olympus",
      "Crisis Core: Final Fantasy VII",
      "Persona 3 Portable",
      "Persona 4 Golden (PSP Import)",
      "Castlevania: The Dracula X Chronicles",
      "Mega Man Powered Up",
      "Metal Gear Solid: Peace Walker",
      "Tactics Ogre: Let Us Cling Together",
    ],
    "ps-vita": [
      "Persona 4 Golden",
      "Gravity Rush",
      "Tearaway",
      "Uncharted: Golden Abyss",
      "Killzone: Mercenary",
      "Danganronpa: Trigger Happy Havoc",
      "Ys: Memories of Celceta",
    ],
    "xbox-series": [
      "Halo Infinite",
      "Forza Horizon 5",
      "Forza Motorsport",
      "Psychonauts 2",
      "Starfield",
      "Sea of Thieves",
      "Hi-Fi Rush",
      "Grounded",
    ],
    "xbox-one": [
      "Halo 5: Guardians",
      "Halo: The Master Chief Collection",
      "Forza Horizon 4",
      "Forza Horizon 3",
      "Ori and the Will of the Wisps",
      "Ori and the Blind Forest",
      "Cuphead",
      "Sunset Overdrive",
    ],
    "xbox-360": [
      "Halo 3",
      "Halo: Reach",
      "Halo 4",
      "Red Dead Redemption",
      "Gears of War",
      "Gears of War 2",
      "Gears of War 3",
      "Bioshock",
      "Orange Box",
      "Mass Effect",
      "Mass Effect 2",
      "Lost Odyssey",
      "Blue Dragon",
    ],
    "xbox-og": [
      "Halo: Combat Evolved",
      "Halo 2",
      "Panzer Dragoon Orta",
      "Jet Set Radio Future",
      "Ninja Gaiden",
      "Conker: Live & Reloaded",
      "Crimson Skies",
    ],
    "genesis": [
      "Sonic the Hedgehog",
      "Sonic the Hedgehog 2",
      "Sonic the Hedgehog 3",
      "Sonic & Knuckles",
      "Castlevania: Bloodlines",
      "Contra: Hard Corps",
      "Streets of Rage 2",
      "Gunstar Heroes",
      "Phantasy Star IV",
      "Shining Force II",
      "Comix Zone",
      "Ristar",
      "Rocket Knight Adventures",
    ],
    "saturn": [
      "Nights into Dreams",
      "Panzer Dragoon Saga",
      "Radiant Silvergun",
      "Guardian Heroes",
      "Castlevania: Symphony of the Night (Saturn)",
      "Burning Rangers",
      "Shining Force III",
    ],
    "dreamcast": [
      "Jet Set Radio",
      "Shenmue",
      "Shenmue II",
      "Skies of Arcadia",
      "Ikaruga",
      "Power Stone 2",
      "Marvel vs. Capcom 2",
      "Sonic Adventure",
      "Sonic Adventure 2",
    ],
    "game-gear": [
      "Sonic the Hedgehog (Game Gear)",
      "Sonic the Hedgehog 2 (Game Gear)",
      "Castlevania: The Adventure",
      "Dragon Crystal",
    ],
    "master-system": [
      "Phantasy Star",
      "Alex Kidd in Miracle World",
      "Sonic the Hedgehog (Master System)",
    ],
    "atari-2600": [
      "Pitfall!",
      "Adventure",
      "Yars' Revenge",
      "Combat",
      "Space Invaders",
      "Asteroids",
      "Berzerk",
    ],
    "jaguar": [
      "Tempest 2000",
      "Alien vs. Predator",
      "Doom (Jaguar)",
    ],
    "pc": [
      "Half-Life 2",
      "Portal",
      "Portal 2",
      "Baldur's Gate 3",
      "Divinity: Original Sin 2",
      "Disco Elysium",
      "Dwarf Fortress",
    ],
    "neo-geo": [
      "Metal Slug",
      "Metal Slug 2",
      "Metal Slug X",
      "The King of Fighters '98",
      "Samurai Shodown II",
      "Garou: Mark of the Wolves",
      "Blazing Star",
    ],
    "turbografx-16": [
      "Bonk's Adventure",
      "Soldier Blade",
      "Gate of Thunder",
      "Dungeon Explorer",
    ],
  },

  "trading-card": {
    "pokemon": [
      "Base Set Booster Pack",
      "Shadowless Base Set Booster Pack",
      "1st Edition Base Set Booster Pack",
      "Base Set 2 Booster Pack",
      "Jungle Booster Pack",
      "Fossil Booster Pack",
      "Team Rocket Booster Pack",
      "Neo Genesis Booster Pack",
      "EX Ruby & Sapphire Booster Pack",
      "Diamond & Pearl Booster Pack",
      "HeartGold & SoulSilver Booster Pack",
      "Black & White Booster Pack",
      "XY Booster Pack",
      "Sun & Moon Booster Pack",
      "Sword & Shield Booster Pack",
      "Scarlet & Violet Booster Pack",
      "Celebrations Booster Pack",
      "Evolving Skies Booster Pack",
      "Brilliant Stars Booster Pack",
      "Silver Tempest Booster Pack",
      "Crown Zenith Booster Pack",
      "Obsidian Flames Booster Pack",
      "Paradox Rift Booster Pack",
      "Temporal Forces Booster Pack",
      "Twilight Masquerade Booster Pack",
      "Shrouded Fable Booster Pack",
      "Stellar Crown Booster Pack",
      "Surging Sparks Booster Pack",
      "Prismatic Evolutions Booster Pack",
    ],
    "mtg": [
      "Alpha Booster Pack",
      "Beta Booster Pack",
      "Unlimited Booster Pack",
      "Revised Booster Pack",
      "Arabian Nights Booster Pack",
      "Antiquities Booster Pack",
      "Legends Booster Pack",
      "The Dark Booster Pack",
      "Fallen Empires Booster Pack",
      "Ice Age Booster Pack",
      "Homelands Booster Pack",
      "Mirage Booster Pack",
      "Tempest Booster Pack",
      "Urza's Saga Booster Pack",
      "Invasion Booster Pack",
      "Odyssey Booster Pack",
      "Onslaught Booster Pack",
      "Mirrodin Booster Pack",
      "Ravnica: City of Guilds Booster Pack",
      "Time Spiral Booster Pack",
      "Lorwyn Booster Pack",
      "Shards of Alara Booster Pack",
      "Zendikar Booster Pack",
      "Innistrad Booster Pack",
      "Return to Ravnica Booster Pack",
      "Theros Booster Pack",
      "Khans of Tarkir Booster Pack",
      "Battle for Zendikar Booster Pack",
      "Shadows over Innistrad Booster Pack",
      "Amonkhet Booster Pack",
      "Ixalan Booster Pack",
      "Dominaria Booster Pack",
      "Guilds of Ravnica Booster Pack",
      "War of the Spark Booster Pack",
      "Throne of Eldraine Booster Pack",
      "Theros Beyond Death Booster Pack",
      "Ikoria Booster Pack",
      "Zendikar Rising Booster Pack",
      "Kaldheim Booster Pack",
      "Strixhaven Booster Pack",
      "Midnight Hunt Booster Pack",
      "Kamigawa: Neon Dynasty Booster Pack",
      "Streets of New Capenna Booster Pack",
      "Dominaria United Booster Pack",
      "The Brothers' War Booster Pack",
      "Phyrexia: All Will Be One Booster Pack",
      "March of the Machine Booster Pack",
      "Wilds of Eldraine Booster Pack",
      "The Lost Caverns of Ixalan Booster Pack",
      "Murders at Karlov Manor Booster Pack",
      "Outlaws of Thunder Junction Booster Pack",
      "Bloomburrow Booster Pack",
      "Duskmourn Booster Pack",
      "Final Fantasy Booster Pack",
    ],
    "yugioh": [
      "Legend of Blue Eyes White Dragon Booster Pack",
      "Metal Raiders Booster Pack",
      "Magic Ruler Booster Pack",
      "Pharaoh's Servant Booster Pack",
      "Labyrinth of Nightmare Booster Pack",
      "Legacy of Darkness Booster Pack",
      "Pharaonic Guardian Booster Pack",
      "Invasion of Chaos Booster Pack",
      "Ancient Sanctuary Booster Pack",
      "Soul of the Duelist Booster Pack",
      "Rise of Destiny Booster Pack",
      "Flaming Eternity Booster Pack",
      "The Lost Millennium Booster Pack",
      "Cybernetic Revolution Booster Pack",
      "Elemental Energy Booster Pack",
      "Shadow of Infinity Booster Pack",
      "Enemy of Justice Booster Pack",
      "Power of the Duelist Booster Pack",
      "Cyberdark Impact Booster Pack",
      "Strike of Neos Booster Pack",
      "Force of the Breaker Booster Pack",
      "Tactical Evolution Booster Pack",
      "Gladiator's Assault Booster Pack",
      "Phantom Darkness Booster Pack",
      "Light of Destruction Booster Pack",
      "The Duelist Genesis Booster Pack",
      "Crimson Crisis Booster Pack",
      "Raging Battle Booster Pack",
      "Ancient Prophecy Booster Pack",
      "Stardust Overdrive Booster Pack",
      "Absolute Powerforce Booster Pack",
    ],
    "one-piece": [
      "Romance Dawn Booster Pack",
      "Paramount War Booster Pack",
      "Pillars of Strength Booster Pack",
      "Kingdoms of Intrigue Booster Pack",
      "Awakening of the New Era Booster Pack",
      "Wings of the Captain Booster Pack",
      "500 Years in the Future Booster Pack",
      "Two Legends Booster Pack",
      "The Four Emperors Booster Pack",
      "Ultra Deck: The Three Captains",
    ],
    "lorcana": [
      "The First Chapter Booster Pack",
      "Rise of the Floodborn Booster Pack",
      "Into the Inklands Booster Pack",
      "Ursula's Return Booster Pack",
      "Shimmering Skies Booster Pack",
      "Azurite Sea Booster Pack",
      "Archazia's Island Booster Pack",
    ],
    "digimon": [
      "Special Booster Ver. 1.0",
      "Special Booster Ver. 1.5",
      "Union Impact Booster Pack",
      "Great Legend Booster Pack",
      "Major to Minor Booster Pack",
      "Double Diamond Booster Pack",
      "Next Adventure Booster Pack",
      "X Record Booster Pack",
      "Across Time Booster Pack",
      "Exceed Apocalypse Booster Pack",
    ],
    "dragon-ball-super": [
      "Series 1 Booster Pack",
      "Series 2 Booster Pack",
      "Series 3 Booster Pack",
      "Series 4 Booster Pack",
      "Series 5 Booster Pack",
      "Series 6 Booster Pack",
      "Malicious Machinations Booster Pack",
      "Clash of Fates Booster Pack",
      "Unison Warrior Series Booster Pack",
    ],
    "star-wars": [
      "Spark of Rebellion Booster Pack",
      "Shadows of the Galaxy Booster Pack",
      "Twilight of the Republic Booster Pack",
      "Skyborn Squadron Booster Pack",
    ],
    "marvel": [
      "Marvel Snap Series 1 Collector's Pack",
      "Upper Deck Marvel Masterpieces Pack",
      "Fleer Ultra X-Men Pack",
      "1990 Impel Marvel Universe Series 1 Pack",
    ],
  },

  "comic": {
    "marvel": [
      "Amazing Fantasy #15 (1st Spider-Man)",
      "Amazing Spider-Man #1 (1963)",
      "Amazing Spider-Man #300 (1st Venom)",
      "X-Men #1 (1963)",
      "Uncanny X-Men #94",
      "Uncanny X-Men #129 (1st Phoenix)",
      "Uncanny X-Men #266 (1st Gambit)",
      "Giant-Size X-Men #1",
      "Avengers #1 (1963)",
      "Avengers #4 (Captain America Returns)",
      "Incredible Hulk #1 (1962)",
      "Incredible Hulk #181 (1st Wolverine)",
      "Iron Man #128 (Demon in a Bottle)",
      "Thor #337 (1st Beta Ray Bill)",
      "Captain America #1 (1941)",
      "Black Panther #1 (1977)",
      "Ms. Marvel #1 (1977)",
      "New Mutants #87 (1st Cable)",
      "New Mutants #98 (1st Deadpool)",
      "Deadpool #1 (1997)",
    ],
    "dc": [
      "Action Comics #1 (1st Superman)",
      "Detective Comics #27 (1st Batman)",
      "Batman #1 (1940)",
      "Superman #1 (1939)",
      "Flash Comics #1 (1st Flash)",
      "Green Lantern #76 (Adams Run)",
      "Batman #232 (1st Ra's al Ghul)",
      "Batman #251 (Joker Cover)",
      "Batman: The Killing Joke (1988)",
      "Watchmen #1",
      "Dark Knight Returns #1",
      "Crisis on Infinite Earths #7 (Death of Supergirl)",
      "Crisis on Infinite Earths #8 (Death of Flash)",
      "Wonder Woman #1 (1942)",
      "Swamp Thing #37 (1st John Constantine)",
      "Saga of the Swamp Thing #21 (Alan Moore)",
      "Preacher #1",
      "Sandman #1",
      "Sandman #8 (Death)",
      "V for Vendetta #1",
    ],
    "image": [
      "Spawn #1",
      "Spawn #9 (1st Angela)",
      "Youngblood #1",
      "WildC.A.T.s #1",
      "Savage Dragon #1",
      "The Walking Dead #1",
      "The Walking Dead #19 (1st Governor)",
      "Saga #1",
      "Invincible #1",
      "East of West #1",
    ],
    "dark-horse": [
      "Aliens #1 (1988)",
      "Predator #1 (1989)",
      "Aliens vs. Predator #0",
      "Sin City #1 (Frank Miller's Sin City)",
      "Hellboy #1",
      "The Mask #1",
      "Star Wars: Dark Empire #1",
    ],
    "idw": [
      "Teenage Mutant Ninja Turtles #1 (IDW)",
      "Transformers: More Than Meets the Eye #1",
      "GI Joe: A Real American Hero #155.5",
      "Locke & Key #1",
      "Humble Bundle TMNT Collection",
    ],
    "boom-studios": [
      "Mighty Morphin Power Rangers #0",
      "Lumberjanes #1",
      "Once & Future #1",
      "Something is Killing the Children #1",
    ],
    "valiant": [
      "X-O Manowar #1 (1992)",
      "Bloodshot #1 (1993)",
      "Ninjak #1 (1994)",
      "Harbinger #1",
      "Shadowman #1 (1992)",
    ],
    "independent": [
      "Teenage Mutant Ninja Turtles #1 (Mirage)",
      "Bone #1",
      "Cerebus #1",
      "Elfquest #1",
    ],
  },

  "funko-pop": {
    "movies": [
      "Darth Vader #01",
      "Luke Skywalker #01",
      "Princess Leia #01",
      "Yoda #02",
      "Chewbacca #03",
      "Stormtrooper #04",
      "Iron Man #04",
      "Captain America #03",
      "Thor #20",
      "Batman #01",
      "Superman #01",
      "The Joker #06",
      "Gandalf #443",
      "Legolas #514",
      "Frodo Baggins #444",
      "Pennywise #55",
      "Freddy Krueger #02",
      "Michael Myers #03",
      "E.T. #31",
      "Marty McFly #49",
    ],
    "tv-shows": [
      "Walter White #08",
      "Heisenberg #160",
      "Jesse Pinkman #09",
      "Jon Snow #07",
      "Daenerys Targaryen #03",
      "Tyrion Lannister #01",
      "The Mandalorian #326",
      "Grogu #368",
      "Michael Scott #871",
      "Dwight Schrute #872",
      "Jim Halpert #873",
      "Bob Ross #560",
      "Eleven #421",
      "Demogorgon #427",
      "Rick Sanchez #113",
      "Morty Smith #114",
    ],
    "games": [
      "Master Chief #05",
      "Link #01",
      "Mario #03",
      "Pikachu #353",
      "Mega Charizard X #337",
      "Sonic #283",
      "Kratos #269",
      "Cloud Strife #35",
      "Vault Boy #05",
      "Dovahkiin #76",
      "Sackboy #03",
      "Crash Bandicoot #273",
    ],
    "anime": [
      "Goku #09",
      "Vegeta #10",
      "Super Saiyan Goku #14",
      "Naruto #71",
      "Kakashi #72",
      "Sasuke #73",
      "Itachi #145",
      "Luffy #98",
      "Zoro #99",
      "Saitama #30",
      "Levi Ackerman #29",
      "Nezuko Kamado #868",
      "Tanjiro Kamado #1193",
      "Deku #248",
      "All Might #249",
      "Killua #188",
      "Gon #189",
    ],
    "sports": [
      "LeBron James #152",
      "Stephen Curry #08",
      "Kobe Bryant (Tribute) #24",
      "Michael Jordan #54",
      "Tom Brady #59",
      "Patrick Mahomes #169",
      "Mike Tyson #01",
      "Muhammad Ali #158",
      "Babe Ruth #02",
      "Derek Jeter #02",
    ],
    "music": [
      "Elvis Presley #03",
      "David Bowie (Ziggy Stardust) #34",
      "Jimi Hendrix #54",
      "Freddie Mercury (Wembley) #183",
      "Michael Jackson #23",
      "Kurt Cobain #66",
      "Elton John #62",
      "Billy Joel #127",
    ],
    "deluxe": [
      "Godzilla (1962) #1468",
      "King Kong vs. Godzilla #1242",
      "Thanos on Throne #289",
      "Hagrid with Harry #01",
    ],
  },

  "lego-set": {
    "star-wars": [
      "Millennium Falcon (75192)",
      "UCS Millennium Falcon (10179)",
      "UCS Star Destroyer (75252)",
      "Death Star (75159)",
      "Death Star II (10143)",
      "Darth Vader's Castle (75251)",
      "Imperial Star Destroyer (6211)",
      "Mos Eisley Cantina (75290)",
      "AT-AT (75313)",
      "Luke Skywalker's X-Wing (75301)",
      "The Razor Crest (75331)",
      "Boba Fett's Starship (75312)",
      "LEGO Star Wars Advent Calendar (75366)",
    ],
    "city": [
      "Police Station (60316)",
      "Fire Station (60320)",
      "Hospital (60330)",
      "Train Station (60335)",
      "Airport (60261)",
      "Space Base and Rocket Launchpad (60351)",
      "Downtown Fire Brigade (60216)",
    ],
    "technic": [
      "Bugatti Chiron (42083)",
      "Lamborghini Sian (42115)",
      "Ferrari Daytona SP3 (42143)",
      "Jeep Wrangler (42122)",
      "Liebherr R 9800 Excavator (42100)",
      "NASA Mars Rover Perseverance (42158)",
    ],
    "creator": [
      "Bookshop (10270)",
      "Botanical Garden (10276)",
      "Ferris Wheel (10247)",
      "Haunted House (10273)",
      "Police Station (10278)",
      "Sanctum Sanctorum (76218)",
    ],
    "super-heroes": [
      "Sanctum Sanctorum (76218)",
      "Daily Bugle (76178)",
      "Batcave Shadow Box (76252)",
      "Wayne Manor (76209)",
      "Avengers Tower (76269)",
      "Spider-Man's House (10784)",
      "Baxter Building (910009)",
    ],
    "harry-potter": [
      "Hogwarts Castle (71043)",
      "Hogwarts Express (75955)",
      "Hogwarts Great Hall (75954)",
      "Diagon Alley (75978)",
      "Hogsmeade Village (76388)",
      "Hogwarts Moment: Potions Class (76383)",
    ],
    "ninjago": [
      "Ninjago City (70620)",
      "Ninjago City Docks (70657)",
      "Ninjago City Gardens (71741)",
      "Fire Dragon Attack (71753)",
    ],
    "ideas": [
      "LEGO Tree House (21318)",
      "Typewriter (21327)",
      "Grand Piano (21323)",
      "Ship in a Bottle (21313)",
      "Pop-Up Book (21315)",
      "Globe (21332)",
      "Motorized Lighthouse (21335)",
      "Dungeons & Dragons: Red Dragon's Tale (21348)",
    ],
    "architecture": [
      "Eiffel Tower (21019)",
      "Burj Khalifa (21031)",
      "Trevi Fountain (21020)",
      "New York City (21028)",
      "Statue of Liberty (21042)",
      "The White House (21054)",
      "Colosseum (10276)",
    ],
    "speed-champions": [
      "Ferrari 812 Competizione (76914)",
      "Lamborghini Huracán (76899)",
      "Porsche 911 Turbo (75888)",
      "McLaren Senna (75892)",
      "Ford GT (75908)",
      "1970 Ferrari 512 M (76906)",
      "Aston Martin Valkyrie (76910)",
    ],
  },

  "coin": {
    "us-coins": [
      "1909-S VDB Lincoln Cent",
      "1914-D Lincoln Cent",
      "1955 Doubled Die Lincoln Cent",
      "1972 Doubled Die Lincoln Cent",
      "1916-D Mercury Dime",
      "1921 Morgan Silver Dollar",
      "1921-D Morgan Silver Dollar",
      "1878-CC Morgan Silver Dollar",
      "1893-S Morgan Silver Dollar",
      "1804 Silver Dollar (Class I)",
      "1794 Flowing Hair Dollar",
      "1916 Standing Liberty Quarter",
      "1932-D Washington Quarter",
      "1932-S Washington Quarter",
      "1955 Proof Set",
      "1950-D Jefferson Nickel",
      "1913 Liberty Head Nickel",
      "1943 Copper Lincoln Cent (Error)",
      "1955 Double Die Lincoln Cent",
    ],
    "world-coins": [
      "1795 French 5 Francs",
      "1900 British Gold Sovereign",
      "1936 Canadian Silver Dollar",
      "1893 Mexican 8 Reales",
      "1875-S Trade Dollar",
      "1916 Panama-Pacific $50 Gold",
      "1912 Canadian Fifty Cent",
    ],
    "ancient-coins": [
      "Alexander the Great Tetradrachm",
      "Julius Caesar Denarius",
      "Athenian Owl Tetradrachm",
      "Roman Sestertius of Marcus Aurelius",
      "Byzantine Solidus",
      "Ptolemaic Gold Mnaieion",
    ],
    "commemoratives": [
      "1986 Statue of Liberty Silver Dollar",
      "1984 Olympic Silver Dollar",
      "1994 World Cup Silver Dollar",
      "2000 Library of Congress $10 Gold",
      "2002 Salt Lake Olympics Silver Dollar",
    ],
    "proof-sets": [
      "1950 U.S. Proof Set",
      "1955 U.S. Proof Set",
      "1960 U.S. Proof Set",
      "1964 U.S. Proof Set",
      "1970-S Small Date Proof Set",
      "1983 Prestige Proof Set",
      "1996-W Proof Set",
    ],
    "error-coins": [
      "1943 Steel Lincoln Cent",
      "1943 Copper Lincoln Cent",
      "1944 Steel Lincoln Cent",
      "1955 Doubled Die Obverse Lincoln Cent",
      "2000 Sacagawea / State Quarter Mule",
      "1999 Wide AM Lincoln Cent",
    ],
    "bullion": [
      "American Gold Eagle 1 oz",
      "American Gold Eagle 1/2 oz",
      "American Gold Eagle 1/4 oz",
      "American Gold Eagle 1/10 oz",
      "American Silver Eagle 1 oz",
      "Canadian Gold Maple Leaf 1 oz",
      "Canadian Silver Maple Leaf 1 oz",
      "South African Krugerrand 1 oz",
      "Austrian Gold Philharmonic 1 oz",
      "Chinese Gold Panda 30g",
    ],
  },

  "sports-card": {
    "baseball": [
      "1952 Topps Mickey Mantle #311",
      "1909 T206 Honus Wagner",
      "1914 Baltimore News Babe Ruth",
      "1963 Topps Pete Rose #537 RC",
      "1989 Upper Deck Ken Griffey Jr. #1 RC",
      "1984 Donruss Don Mattingly #248 RC",
      "1984 Fleer Update Roger Clemens #U-27 RC",
      "1993 SP Derek Jeter #279 RC",
      "2001 Bowman Chrome Albert Pujols RC",
      "2011 Bowman Chrome Mike Trout #175 RC",
      "2018 Topps Update Shohei Ohtani RC",
      "1955 Topps Roberto Clemente #164 RC",
    ],
    "basketball": [
      "1986 Fleer Michael Jordan #57 RC",
      "1980 Topps Larry Bird / Magic Johnson RC",
      "2003 Upper Deck LeBron James RC",
      "2003 Topps Chrome LeBron James RC",
      "2009 Steph Curry Topps Chrome RC",
      "2018 Luka Doncic Optic RC",
      "2019 Ja Morant Mosaic RC",
      "2012 Panini Prizm Giannis Antetokounmpo RC",
      "1984 Star Company Michael Jordan #195 RC",
      "1996 Topps Chrome Kobe Bryant RC",
    ],
    "football": [
      "1958 Topps Jim Brown #62 RC",
      "1935 National Chicle Bronko Nagurski #34",
      "1969 Topps OJ Simpson RC",
      "1979 Topps Jerry Rice (NONE, first regular issue 1986)",
      "1986 Topps Jerry Rice RC",
      "2000 Playoff Contenders Tom Brady #144 RC",
      "2012 Panini Prizm Russell Wilson RC",
      "2016 Donruss Dak Prescott RC",
      "2017 Panini Prizm Patrick Mahomes RC",
      "2018 National Treasures Lamar Jackson RC",
    ],
    "hockey": [
      "1966 Topps Bobby Orr #35 RC",
      "1979 OPC Wayne Gretzky #18 RC",
      "1990 Score Eric Lindros #440 RC",
      "2005 Upper Deck Sidney Crosby RC",
      "2015 Upper Deck Connor McDavid RC",
      "2018 O-Pee-Chee Platinum Cale Makar RC",
      "2021 Upper Deck Connor Bedard RC",
    ],
    "soccer": [
      "1958 Pelé (Alifabolaget) RC",
      "1966 A&BC Diego Maradona RC",
      "2004 Topps Chrome Cristiano Ronaldo RC",
      "2004 Topps Chrome Lionel Messi RC",
      "2018 Panini Prizm Kylian Mbappé RC",
      "2019 Panini Prizm Erling Haaland RC",
      "2019 Panini Prizm Jude Bellingham RC",
    ],
    "golf": [
      "2001 Upper Deck Tiger Woods #1 RC",
      "1997 Grand Slam Ventures Tiger Woods Amateur RC",
      "2012 SP Authentic Rory McIlroy RC",
      "2012 SP Authentic Jordan Spieth RC",
    ],
    "mma": [
      "2009 Topps UFC Round 1 Jon Jones RC",
      "2010 Topps UFC Conor McGregor RC",
      "2012 Topps UFC Khabib Nurmagomedov RC",
      "2017 Topps UFC Nunes RC",
    ],
    "wrestling": [
      "2007 Topps Heritage WWE John Cena",
      "2014 Topps WWE Roman Reigns RC",
      "2012 Leaf Originals Wrestling CM Punk",
      "2016 Topps WWE Bayley RC",
    ],
    "multi-sport": [
      "2012 Panini Prizm USA Olympics Set",
      "2020 Topps Chrome Update Ben Simmons / Jaylen Brown",
    ],
  },
};

export function getCatalogItems(category: Category, subcategory?: string): string[] {
  const catData = catalog[category];
  if (!catData) return [];

  if (subcategory && catData[subcategory]) {
    return catData[subcategory];
  }

  // No subcategory selected — return all items flattened
  return Object.values(catData).flat();
}
